import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";

import Navbar from "@/components/navbar";
import ThemeProvider from "@/context/Theme";

const OpenSans = localFont({
  variable: "--font-open-sans",
  src: "/fonts/OpenSansVF.ttf",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${OpenSans.variable} bg-white/60 antialiased dark:bg-zinc-900`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            <Navbar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
